//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMasterOrange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public int product_id { get; set; }
        public string comment_text { get; set; }
        public int rating { get; set; }
        public System.DateTime comment_date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual product product { get; set; }
    }
}
