//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMasterOrange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_details = new HashSet<order_details>();
            this.payments = new HashSet<payment>();
        }
    
        public string order_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public System.DateTime order_date { get; set; }
        public string delivery_address { get; set; }
        public string delivery_phone { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<int> state_id { get; set; }
        public string payment_type { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual guest guest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual order_states order_states { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
    }
}
